### ISSUE TITLE
数据解析报错

### ISSUE THREAD

**Issue by zkdengta** [fluttercandies/flex_grid#3]
### Platforms

dart

### Description

FormatException: Unexpected character (at character 1)
MapEntry(Simple: [Instance of 'DemoRouteResult', Instance of 'DemoRouteRe...
      #0      _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1383:5)
      #1      _ChunkedJsonParser.parseNumber (dart:convert-patch/convert_patch.dart:1250:9)
      #2      _ChunkedJsonParser.parse (dart:convert-patch/convert_patch.dart:915:22)
      #3      _parseJson (dart:convert-patch/convert_patch.dart:35:10)
      #4      JsonDecoder.convert (dart:convert/json.dart:610:36)
      #5      JsonCodec.decode (dart:convert/json.dart:216:41)
      #6      FFConvert.convert.<anonymous closure> (package:ff_annotation_route_library/src/helper.dart:17:17)
      #7      asT (package:ff_annotation_route_library/src/helper.dart:42:33)
      #8      getRouteSettings.<anonymous closure> (package:example/example_route.dart:99:21)

### My code

FormatException: Unexpected character (at character 1)
MapEntry(Simple: [Instance of 'DemoRouteResult', Instance of 'DemoRouteRe...
      #0      _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1383:5)
      #1      _ChunkedJsonParser.parseNumber (dart:convert-patch/convert_patch.dart:1250:9)
      #2      _ChunkedJsonParser.parse (dart:convert-patch/convert_patch.dart:915:22)
      #3      _parseJson (dart:convert-patch/convert_patch.dart:35:10)
      #4      JsonDecoder.convert (dart:convert/json.dart:610:36)
      #5      JsonCodec.decode (dart:convert/json.dart:216:41)
      #6      FFConvert.convert.<anonymous closure> (package:ff_annotation_route_library/src/helper.dart:17:17)
      #7      asT (package:ff_annotation_route_library/src/helper.dart:42:33)
      #8      getRouteSettings.<anonymous closure> (package:example/example_route.dart:99:21)

### Try do it

FormatException: Unexpected character (at character 1)
MapEntry(Simple: [Instance of 'DemoRouteResult', Instance of 'DemoRouteRe...
      #0      _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1383:5)
      #1      _ChunkedJsonParser.parseNumber (dart:convert-patch/convert_patch.dart:1250:9)
      #2      _ChunkedJsonParser.parse (dart:convert-patch/convert_patch.dart:915:22)
      #3      _parseJson (dart:convert-patch/convert_patch.dart:35:10)
      #4      JsonDecoder.convert (dart:convert/json.dart:610:36)
      #5      JsonCodec.decode (dart:convert/json.dart:216:41)
      #6      FFConvert.convert.<anonymous closure> (package:ff_annotation_route_library/src/helper.dart:17:17)
      #7      asT (package:ff_annotation_route_library/src/helper.dart:42:33)
      #8      getRouteSettings.<anonymous closure> (package:example/example_route.dart:99:21)

**Comment by zmtzawqlp** [comment]
master上面的代码吗？

**Comment by zkdengta** [comment]
是的

**Comment by zmtzawqlp** [comment]
好了。试试
